models/user.js

added user schema

---

models/club.js

added club schema

---

models/event.js

added event schema

---

models/club.js
models/event.js
models/user.js
package-lock.json
package.json

changed models

---

.env.dev
index.js
package-lock.json
package.json
server.js
utils/db.js

added config

---

.env.dev
middleware/auth.js
utils/auth.js
utils/db.js

added auth middleware

---

Routes/user/index.js
controllers/user.js
middleware/auth.js
models/user.js
utils/auth.js

added user routes

---

controllers/user.js
utils/auth.js

jwt issue resolved

---

Routes/club/index.js
Routes/event/index.js
controllers/crud.js

Signed-off-by: Vinayak Sharma <vinayaksh42@gmail.com>

controllers

---

Routes/club/index.js
Routes/user/index.js
controllers/club.js
controllers/user.js
models/club.js

added login route

---

Routes/club/index.js
controllers/club.js

added join endpoint

---

controllers/club.js

updated join controller

---

controllers/club.js
routes/club.js
routes/event.js
routes/user.js

added leave route and refactored

---

controllers/club.js
routes/club.js

added addteam route

---

controllers/club.js
routes/club.js

added routes for club

---

controllers/club.js
controllers/event.js
controllers/user.js
models/event.js
routes/club.js
routes/event.js
routes/user.js

added event controllers

---

controllers/user.js

updated login route

---

controllers/user.js

added error messages

---

package-lock.json
package.json
utils/mail.js

added nodemailer

---

.github/pull_request_template.md

Any suggestions or changes are welcome @codetheorem @vinayaksh42

Pull Request template added, solves #32

---

controllers/club.js
controllers/event.js
package-lock.json
package.json
utils/upload.js

added multer

---

controllers/user.js
package-lock.json
package.json

- added the password pattern validation for the signup page.
- used the complexity module in the node
- minimum of 8 character needed and a maximum of 16
- requires: 1 uppercase
- 1 lowercase
- 1 special character (@ # ! and many  #more)
- 1 digit (0 to 9)
- `npm install complexity`
Original | Updated
:------------------:|:------------------:
original screenshot | updated screenshot

fixed the issue #34

---

.all-contributorsrc
README.md

Contributors :)
